spring.application.name=model
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudstorage
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate (The ORM Magic)
# "update" checks your entities and modifies the DB schema automatically.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits (Important for later)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#JWT Secret Key
# The secret key bridge (You probably already have this)
application.security.jwt.secret-key=${JWT_SECRET}

# ADD THIS LINE: The expiration bridge
application.security.jwt.expiration=${JWT_EXPIRATION_TIME}

# Local Storage Configuration
file.upload-dir=uploads
server.port=8081
