package com.cloudstorage.model.service;

import java.time.LocalDateTime;

import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.cloudstorage.model.config.AppRole;
import com.cloudstorage.model.dto.loginDTO.AuthResponseDTO;
import com.cloudstorage.model.dto.loginDTO.LoginRequestDTO;
import com.cloudstorage.model.dto.loginDTO.RegisterRequestDTO;
import com.cloudstorage.model.dto.loginDTO.RegisterResponseDTO;
import com.cloudstorage.model.entity.Users;
import com.cloudstorage.model.repository.UserRepository;

import lombok.AllArgsConstructor;

@Service
@AllArgsConstructor
public class AuthServiceImpl implements AuthService {
    private UserRepository userRepository;
    private PasswordEncoder passwordEncoder;
    private AuthenticationManager authenticationManager; //provinding interrogation room
    private JWTService jwtService;

    @Override
    public AuthResponseDTO loginUser(LoginRequestDTO loginRequestDTO) {
        //magic does all the work of check the plain text to hash password
        //Authentication Token gets build up -> Unauthenticated token
        authenticationManager.authenticate(
            new UsernamePasswordAuthenticationToken(loginRequestDTO.getEmail(), loginRequestDTO.getPassword())
        );
        //

        //User Verified
        String jwtToken = jwtService.generateToken(loginRequestDTO.getEmail());
        return new AuthResponseDTO(jwtToken);
    }
    
    @Override
    public RegisterResponseDTO saveUser(RegisterRequestDTO registerDTO) {
        // 1. Fetch email
        String email = registerDTO.getEmail();

        // 2. Check if user Exists
        if (userRepository.existsByEmail(email)) {
            throw new RuntimeException("Email is already registered. Please login.");
        }

        // 3. Hash the password
        String hashedPassword = passwordEncoder.encode(registerDTO.getPassword());

        // 4. Construct Entity
        Users user = new Users();
        user.setEmail(email);
        user.setPassword(hashedPassword);
        user.setRole(AppRole.USERS); // Defaulting to standard user
        user.setCreatedAt(LocalDateTime.now());
        user.setUpdatedAt(LocalDateTime.now());
        // Note: Assuming UUID is auto-generated by JPA/Hibernate annotations in the
        // Entity

        // 5. Save to Database
        userRepository.save(user);

        // 6. Create and return the safe Response DTO
        return new RegisterResponseDTO(
                user.getId(),
                email,
                user.getCreatedAt(),
                user.getUpdatedAt(),
                user.getRole());
    }
}
